### ISSUE TITLE
HÜ Kommentar

### ISSUE THREAD

**Issue by MaurederChristoph** [Teaching-HTL-Leonding/console-chart-quiz-MaurederChristoph#1]
Sehr geehrter Herr prof. @rstropek ,

ich habe beide extra Aufgaben gelöst um meinen Code auszugleichen.
Ich habe mich bemüht die Aufgabe so gut wie möglich zu bewältigen und mir ist bewusst das das Ergebnis 
nicht ansprechend zu Lessen ist und auch anderwärtig noch Mängel aufweist.

**Comment by rstropek** [comment]
Well done. We discussed an efficient solution with LINQ in the last exercise. Note: The `ConsoleChartQuiz` would be a good application of C# 9's new `record` type. However, it is not optimal because you hard-coded the column in the text file in this class. Therefore, you app is not generically usable for analyzing any text file.
